### ISSUE TITLE
Broken "step by step" link in Orientation guide

### ISSUE THREAD

**Issue by mhnap** [rust-lang-ua/rust_incubator#25]
## Summary
Broken link in [Orientation](https://github.com/rust-lang-ua/rust_incubator/blob/master/orientation.md) guide.

## Steps to reproduce
1. Open [Orientation](https://github.com/rust-lang-ua/rust_incubator/blob/master/orientation.md) guide.
2. Navigate to [Getting Started](https://github.com/rust-lang-ua/rust_incubator/blob/master/orientation.md#getting-started) section.
3. Click on [step by step](https://github.com/rust-lang-ua/rust_incubator/blob/master/how_to_start.md).

## What is the current _bug_ behavior?
404 - page not found

## What is the expected _correct_ behavior?
I think link should be to [how_to_fork](https://github.com/rust-lang-ua/rust_incubator/blob/master/how_to_fork.md) file.

## Relevant logs and/or screenshots
![image](https://github.com/rust-lang-ua/rust_incubator/assets/17296656/c3f7fccd-854a-4121-b0ba-bd563e58ed8f)

## Possible fixes
Use correct link.

**Comment by Wandalen** [comment]
Thank you 🙏
Fixed!
