### ISSUE TITLE
Broken "Fast" link in Orientation guide

### ISSUE THREAD

**Issue by mhnap** [rust-lang-ua/rust_incubator#26]
## Summary
Broken link in [Orientation](https://github.com/rust-lang-ua/rust_incubator/blob/master/orientation.md) guide.

## Steps to reproduce
1. Open [Orientation](https://github.com/rust-lang-ua/rust_incubator/blob/master/orientation.md) guide.
2. Navigate to [Why Rust](https://github.com/rust-lang-ua/rust_incubator/blob/master/orientation.md#why-rust) section.
3. Click on [Fast](https://github.com/rust-lang-ua/rust_incubator/blob/master/%D0%A8%D0%B2%D0%B8%D0%B4%D0%BA%D0%B8%D0%B9).

## What is the current _bug_ behavior?
404 - page not found

## What is the expected _correct_ behavior?
I don't know, but not 404 :)

## Relevant logs and/or screenshots
![image](https://github.com/rust-lang-ua/rust_incubator/assets/17296656/7d2e2620-0f6a-4fdc-b913-9dfe7d184ed7)

## Possible fixes
Use correct link.

**Comment by Wandalen** [comment]
Thank you 🙏
