### ISSUE TITLE
Link correction?

### ISSUE THREAD

**Issue by fiberether** [rust-lang-ua/rust_incubator#33]
[In section 3.10](https://github.com/rust-lang-ua/rust_incubator/tree/master/3_ecosystem/3_10_threads)

I noticed the hypertext has its text part as `TLS`, but the underlying link leads to `Asynchronous I/O` article in wikipedia
This part is shown by arrow on the image below.

Is this right or indeed - a mistake?

---
<img width="1064" alt="Screenshot 2023-07-06 at 06 21 21" src="https://github.com/rust-lang-ua/rust_incubator/assets/65344944/36941cb2-77c5-4d23-b2df-ce9287f97a84">

**Comment by sokyrko** [comment]
cc @Wandalen
